### ISSUE TITLE
[Question] Does it have Vl61 support? And if no, is it comming any soon?

### ISSUE THREAD

**Issue by sTiKyt** [abridgewater/alesisvsysex#11]

**Comment by abridgewater** [comment]
VI61 should work, more or less.

Saving might be a touch unreliable still, as the MIDI stack selected by the original author turns out to be missing a critical synchronization operation, so I had to take an approach of "add an appropriate delay and hope for the best" (see issue #10 ).

The MIDI-to-DIN controls are, IIRC, not displayed, and there may be other issues with the overall UI and control mapping.

Only one configuration slot is supported (see issue #1 ).

The configuration files _should_ be compatible with the "official" configuration editor.

I have no plans for further work on this project at this time.

**Comment by sTiKyt** [comment]
Thanks for quick answer!
